### ISSUE TITLE
Fix english translations, add proper code comments & remove binary zip files from repository due to unversionable format

### ISSUE THREAD

**Issue by ilbuonmarcio** [CastellaniDavide/Compass-MarconiVr#1]

**Comment by DavideC03** [comment]
Where I have to fix my english?
And who are you?

**Comment by ilbuonmarcio** [comment]
On README, for example

**Comment by ilbuonmarcio** [comment]
I just found your repo linked to a friend of mine, and checking it out I found some areas worth of improvements

Remember to add a license to the project btw
